### ISSUE TITLE
请问一下这个勇者标识是什么？

### ISSUE THREAD

**Issue by ty-peng** [GSWXXN/HideDEVIcon#1]

**Comment by GSWXXN** [comment]
勇士图标现在已经没有了，去年MIUI13之前的安卓12设备会有个机器人图标占用状态栏。 

这个模块还可以把手机管家的电池温度显示回具体数值，只要作用域勾选手机管家就好，不用勾选系统界面

**Comment by ty-peng** [comment]
OK 3Q
